---
title: "clases R"
author: "Andrée Euribe"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Diseños experimentales

## DCA: diseño completamente al azar

Dosis de fertilización nitrogenada:

- 0
- 50
- 100
- 150
Rep:5

```{r}
# Cargar el paquete
library(agricolae)

# Definir los niveles de los factores
factores <- c(0, 50, 100, 150)

# Número de repeticiones
replicaciones <- 5

# Crear el diseño DCA
dca <- design.crd(trt = factores, r = replicaciones)

# Mostrar el diseño
print(dca)

# Si deseas visualizar el diseño en forma de tabla
tabla_diseño <- as.data.frame(dca)
colnames(tabla_diseño) <- c("Replication", "Treatment")
print(tabla_diseño)


# Aquí puedes añadir tus datos de respuesta
# Suponiendo que tienes un vector 'respuestas' con tus datos
# respuestas <- c(...)  # Aquí irían tus datos de respuesta

# Agregar los datos de respuesta al diseño
# dca$data <- respuestas

# Realizar análisis de varianza (ANOVA)
# anova_result <- aov(respuestas ~ as.factor(tratamientos), data=dca)
# summary(anova_result)

# Realizar pruebas de comparación de medias
# HSD_result <- HSD.test(anova_result, "tratamientos", group=TRUE)
# print(HSD_result)


```


##DBCA
Factor 1 (dosis de nitrogeno): 0,50,100,150
Factor 2 (variedades de papa): canchan y peruanita
Bloques: 5
```{r}
library(agricolae)

factores <- c(0, 50, 100, 150)
variedad <- c("canchan","peruanita")
trt<-c(4,2) # factorial 3x2
outdesign <-design.ab(trt, r=5)

str(outdesign)
book<-outdesign$book
book
#head(book,30) # print of the field book
```

#Analisis de datos


```{r}
#library(tidyverse)
#library(googlesheets4)

library(readxl)
fb <- read_excel("LA MOLINA 2014 POTATO WUE (FB).xlsx", 
                                            sheet = "fb")

View(fb)
str(fb)

```

##Importar datos

```{r}
#url <- "https"
#gs <- as_sheets_id(url)
#fb <- range_read(gs,"fb")
```

##Modelo estadistico
```{r}
modelo <- aov(formula = lfa ~ riego + geno + riego*geno + block, data = fb)
plot(modelo)
anova(modelo)
```

##Comparacion de medias
```{r}
library(agricolae)
mc <- agricolae::duncan.test(modelo, trt=c("riego","geno"))
mc
str(mc)
```


```{r}
#plot(mc)
library(emmeans)
library(multcomp)
mc <- emmeand(model, ~riego | geno) %>%
  cld(Letter = letters, reversed = T)
mc

```


##Grafico
```{r}
library(inti)
plot_smr(data = mc, type = "bar", x = "geno", y = "emmean", group = "riego", sig = ".group", error = "SE", ylimits = c(0, 12000, 2000))
##ggplot(mc, aes(x = geno, y = emmean, fill = riego)) + geom_bar(stat = "identity") + theme_minimal() + labs(title = "Grafico de barras", x = "Categoria", y = "valores")

```





